### ISSUE TITLE
Use the new React SDK by Auth0 instead of the old implementation

### ISSUE THREAD

**Issue by sleepyArpan** [jamesqquick/dev-setups#17]

**Comment by sleepyArpan** [comment]
Hi @jamesqquick ,
I am working on this right now and the current SDK API doesnt have a `onRedirectCallback` prop for the Auth0 Provider. I have installed the sdk in the project and have replaced the `useAuth0()` calls with the one from the SDK but the app seems to crash as soon as I hit the login button. How should I go forward with this?

**Comment by jamesqquick** [comment]
@sleepyArpan can you push that branch so I can run it myself and take a look?

**Comment by sleepyArpan** [comment]
Great! I will create a PR with some notes to the changes I made. :)
